---
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2026.1.0
    container_name: home-assistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - home_assistant_data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: America/New_York

volumes:
  home_assistant_data:
