---
services:
  mongodb:
    image: mongo:6.0.19
    container_name: graylog-mongodb
    restart: unless-stopped
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - graylog

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: graylog-opensearch
    restart: unless-stopped
    volumes:
      - "opensearch_data:/usr/share/opensearch/data"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog

  graylog:
    image: graylog/graylog:6.3.6
    container_name: graylog
    restart: unless-stopped
    depends_on:
      - mongodb
      - opensearch
    volumes:
      - "graylog_data:/usr/share/graylog/data"
    environment:
      - "GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id"
      - "GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000"
      - "GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200"
      - "GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog"
      - "GRAYLOG_REPORT_DISABLE_SANDBOX=true"
      - "GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}"
      - "GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}"
      - "GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}"
      - "GRAYLOG_HTTP_PUBLISH_URI=${GRAYLOG_HTTP_PUBLISH_URI}"
    ports:
      - "9000:9000/tcp"  # Graylog web interface and REST API
      - "5044:5044/tcp"  # Beats
      - "5140:5140/tcp"  # Syslog TCP
      - "5140:5140/udp"  # Syslog UDP
      - "12201:12201/tcp"  # GELF TCP
      - "12201:12201/udp"  # GELF UDP
      - "13301:13301/tcp"  # Forwarder data
      - "13302:13302/tcp"  # Forwarder config
    networks:
      - graylog
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"

networks:
  graylog:

volumes:
  mongodb_data:
  opensearch_data:
  graylog_data:
