---
# Basic environment setup
ansible_python_interpreter: /usr/bin/python3
ansible_user: lbp
timezone: America/New_York
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKqPuTyh0IOltid4FiEH76niboJvZ0iIGp2C/H1jtXwy ben@prisby.com"
common_packages:
  - avahi-daemon
  - build-essential
  - ca-certificates
  - cifs-utils
  - curl
  - dnsutils
  - git
  - locales-all
  - pipx
  - python-is-python3
  - python3
  - python3-debian
  - python3-pip
  - unattended-upgrades
  - vim
pipx_packages:
  - ansible
  - ansible-lint
  - pre-commit

# chezmoi configuration
chezmoi_repo: https://github.com/benprisby/dotfiles

# NUT configuration
nut_client_ups: ups
nut_client_server: "{{ hostvars['big-slice']['ansible_host'] }}"
nut_client_username: "{{ vault_nut_monitor_username }}"
nut_client_password: "{{ vault_nut_monitor_password }}"

# Docker configuration
docker_projects_path: "/home/{{ ansible_user }}/docker"
docker_users:
  - "{{ ansible_user }}"
docker_daemon_syslog_address: "{{ hostvars['big-slice']['ansible_host'] }}"
docker_daemon_options:
  log-driver: syslog
  log-opts:
    syslog-address: "udp://{{ docker_daemon_syslog_address }}:5140"
    syslog-facility: daemon
    syslog-format: rfc5424micro
    tag: "{{ '{{.DaemonName}}/{{.Name}}/{{.ID}}' | string }}"
  metrics-addr: "0.0.0.0:9323"
