---
services:
  homebridge:
    image: homebridge/homebridge:2025-11-27
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge_data:/homebridge

volumes:
  homebridge_data:
