---
# Main infrastructure server
hardware:
  model: Intel NUC
  type: nuc

docker_services:
  - graylog
  - home-assistant
  - homepage
  - jellyfin
  - monitoring
  - nginx-proxy-manager
  - nut-server
  - portainer

# NUT configuration override for local server
nut_client_server: 127.0.0.1

# Docker configuration override for local syslog server
docker_daemon_syslog_address: 127.0.0.1
