---
services:
  portainer-agent:
    image: portainer/agent:2.38.1
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    ports:
      - "9001:9001"
